server:
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: wzwPortal
  profiles:
    active: test

---
#正式环境
spring:
  application:
    name: wzwPortal-pro
  profiles: pro
server:
  port: 9527

---
#测试环境
spring:
  application:
    name: wzwPortal-test
  profiles: test
server:
  port: 8198